name: 17 - Custom Actions - Composite
run-name: "17: 01 - Custom Actions - Composite | Environment: ${{ inputs.target-env }}"

on:
  workflow_dispatch: 
    inputs:
      target-env:
        description: The environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 17-custom-actions/react-app  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node.js and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 22.x
          working-directory: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      - name: Test
        run: |
          npm run test
      - name: Build
        run: |
          npm run build